[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[options]
install_requires = [
    "numpy",
    "pandas",
    "bokeh",
    "scipy",
    "ipywidgets",
    "ipyfilechooser"
]